// Generated by scripts/gen-song-previews.mjs — do not edit by hand.
// The 30s preview clips for the songs in content.ts, pinned so the page never has to ask
// iTunes at runtime (it rate-limits bursts, which greys the play buttons out). A song
// missing from here falls back to a live lookup through /api/preview.
export const SONG_PREVIEWS: Record<string, string> = {
	"Creature (w/ Orchestra)": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/d9/1d/1d/d91d1d8b-ee1c-64cc-7597-769620104066/mzaf_11072355618262242319.plus.aac.p.m4a",
	"Nobody": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/ec/92/81/ec928101-040f-b717-e7cf-6adc4147f6da/mzaf_1756733247751089452.plus.aac.p.m4a",
	"Ankles": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/4d/bc/df/4dbcdf01-77a1-5fd8-d006-692e54f3ac00/mzaf_11089630832750794239.plus.aac.p.m4a",
	"Banana Pancakes": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/88/66/4f/88664fb9-de4e-ae0f-c552-063c7a6df47d/mzaf_2779752966584665566.plus.aac.p.m4a",
	"Fade Into You": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/4c/db/e8/4cdbe88c-b737-617d-0c1c-35ba36445750/mzaf_4038354414747356567.plus.aac.p.m4a",
	"Angry Young Man": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/12/ab/1b/12ab1b0c-c9c2-8c87-4383-657d7bd5426f/mzaf_13156830507331122148.plus.aac.p.m4a",
	"First Love / Late Spring": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/fd/44/38/fd4438dc-a1ef-6942-346f-db68e8511fca/mzaf_10414107169942300844.plus.aac.p.m4a",
	"Vampire Empire": "https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/4f/0d/05/4f0d0569-3b8c-4307-8466-49e658799800/mzaf_12961803786530764378.plus.aac.p.m4a"
};
